from sqlalchemy import Column, Integer, String, Boolean, DateTime, Text, Enum as SQLEnum, ForeignKey
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.core.database import Base
import enum


class CertificateType(str, enum.Enum):
    MACHINE = "machine"
    USER = "user"
    SERVER = "server"


class CertificateStatus(str, enum.Enum):
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    REVOKED = "revoked"


class Certificate(Base):
    __tablename__ = "certificates"
    
    id = Column(Integer, primary_key=True, index=True)
    serial_number = Column(String, unique=True, index=True, nullable=False)
    
    # Certificate info
    certificate_type = Column(SQLEnum(CertificateType), nullable=False)
    common_name = Column(String, nullable=False)
    subject_alternative_names = Column(Text, nullable=True)  # JSON array as text
    
    # Status
    status = Column(SQLEnum(CertificateStatus), default=CertificateStatus.PENDING, nullable=False)
    
    # Certificate data
    csr = Column(Text, nullable=True)  # PEM encoded CSR
    certificate = Column(Text, nullable=True)  # PEM encoded certificate
    
    # Validity
    not_before = Column(DateTime(timezone=True), nullable=True)
    not_after = Column(DateTime(timezone=True), nullable=True)
    validity_days = Column(Integer, nullable=False)
    
    # Revocation
    revoked_at = Column(DateTime(timezone=True), nullable=True)
    revocation_reason = Column(String, nullable=True)
    
    # Relations
    requested_by_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    requested_by = relationship("User", foreign_keys=[requested_by_id])
    
    approved_by_id = Column(Integer, ForeignKey("users.id"), nullable=True)
    approved_by = relationship("User", foreign_keys=[approved_by_id])
    
    revoked_by_id = Column(Integer, ForeignKey("users.id"), nullable=True)
    revoked_by = relationship("User", foreign_keys=[revoked_by_id])
    
    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    approved_at = Column(DateTime(timezone=True), nullable=True)
    
    # Auto-approval flag (for machine/user certs generated by admins)
    auto_approved = Column(Boolean, default=False, nullable=False)